### ISSUE TITLE
Fix typos in licence comments

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#73] opened 2016-08-23 20:02 UTC
I suggest to replace a word like "`lincensed`" by "`licenced`" in some source files.

**Comment by elfring** [comment] 2017-06-08 15:18
It seems that there are 164 source code places left over which might need another look.

**Comment by JuliaLawall** [comment] 2017-06-08 19:01
On Thu, 8 Jun 2017, Markus Elfring wrote:

>
> It seems that there are 164 source code places left over which might need
> another look.

Since you have gone to the trouble of counting them, why not fix them, or
at least say what the issue is.

julia

**Comment by elfring** [comment] 2017-06-09 07:46
>Since you have gone to the trouble of counting them,

This counting was easy because of a simple search for a questionable word.


>why not fix them,

I imagine that it can be a bit harder to achieve consensus for the adjustment of licence information.
[You integrated some changes already](https://github.com/coccinelle/coccinelle/commit/72c2849aeaa135a6ee1eab8119c4d5d3603233f1 "Fixed some spelling errors") on 2016-10-22.


>or at least say what the issue is.

I dared to report my doubts for the word “`lincensed`” on 2016-08-23. How can the remaining update candidates clarified?

**Comment by elfring** [comment] 2017-06-11 10:05
I would have found it nicer if you would refer to the relevant issue number in a few of your commits (from 2017-06-09 for example).
* [A](https://github.com/coccinelle/coccinelle/commit/1c4474890c065711b16c7d02089a56da5a07e13a)
* [B](https://github.com/coccinelle/coccinelle/commit/bca1e4eb9d305ed37d884070d970ea19f35c2377)

Was it needed to split such a change?

**Comment by elfring** [comment] 2017-06-12 13:06
Should I try a corresponding pull request for the replacement of the mentioned word at remaining 39 places?

**Comment by vgambier** [comment] 2024-11-29 11:32
fixed in ff57802f

**Closed by vgambier** 2024-11-29 11:32 UTC
