### ISSUE TITLE
config.status: error: cannot find input file: `bundles/pcre/pcre-ocaml/src/pcre.ml.in'

### ISSUE THREAD

**Issue by deval-vekaria** [coccinelle/coccinelle#301] opened 2023-03-13 21:20 UTC
doing ./configure linux/arm64/v8
shoots below error

config.status: error: cannot find input file: `bundles/pcre/pcre-ocaml/src/pcre.ml.in'

**Comment by JackyCZJ** [comment] 2023-04-25 03:34
I got the same problem , solve by 
```shell
sudo apt install libparmap-ocaml
sudo apt install ocaml-findlib
```

**Comment by JuliaLawall** [comment] 2023-04-25 05:57
On Mon, 24 Apr 2023, Jacky Chan wrote:

>
> I got the same problem , solve by
>
> sudo apt install libparmap-ocaml
> sudo apt install ocaml-findlib


Thanks for helping.

julia

**Comment by kees** [comment] 2023-05-01 20:43
Ah, solved with "sudo apt install libpcre-ocaml-dev"

**Comment by sregister** [comment] 2023-05-17 02:34
I was able to reproduce this on Rocky 9, unfortunately I couldn't find `libpcre-ocaml-dev` or similar package in EPEL9 or any of the other repos. I was able to work around this by checking out the last v1.1.1 tag from the repo so I imagine this is some sort of regression

**Comment by JuliaLawall** [comment] 2023-05-17 06:38
On Tue, 16 May 2023, Scott Register wrote:

>
> I was able to reproduce this on Rocky 9, unfortunately I couldn't find
> libpcre-ocaml-dev or similar package in EPEL9 or any of the other repos. I
> was able to work around this by checking out the last v1.1.1 tag from the
> repo so I imagine this is some sort of regression

Thanks for the report.  Will look into it.

julia

**Comment by vgambier** [comment] 2024-11-19 15:49
Additionally, on Debian and Ubuntu, using opam to switch OCaml versions results in conflicts, with some of the -ocaml-dev packages:

	File "globals/regexp_pcre.ml", line 1:
	Error: /usr/lib/ocaml/pcre/pcre.cmi
	       is not a compiled interface for this version of OCaml.
	It seems to be for an older version of OCaml.

> The same happens to me on Arch Linux starting from commit [f9e2552](https://github.com/coccinelle/coccinelle/commit/f9e2552d40522524a17e066fd241200dfc6e78c4).

Interesting. I also wanted to add installation instructions for Arch, but I don't have immediate access to an Arch system right now.

Anyhow-- I will try to look into this.

**Comment by vgambier** [comment] 2024-11-20 15:40
@gentoo-root  On a brand-new Arch install, on 0e82e2d, after installing

```$ pacman -Syu pkg-config patch opam ocaml ocaml-findlib autoconf automake pcre make gcc```

and using OCaml 5.1.0 (via opam)

```
$ opam init
$ opam switch create 5.1.0
$ eval $(opam env --switch=5.1.0 --set-switch)
```

I managed to build Coccinelle (without scripting capabilities). Let me know if you are still having trouble.

**Comment by vgambier** [comment] 2024-12-18 16:38
Original issues were fixed.
Newer atest pcre issue is fixed by installing libpcre3-dev. Latest parmap issue:

**Comment by vgambier** [comment] 2024-12-18 16:46
Original issues were fixed.
Newer pcre issue is fixed by installing libpcre3-dev.
Newer parmap issue is not yet fixed.

**Closed** 2024-12-19 13:42 UTC
